### ISSUE TITLE
Please do a better job in adding the itsyou online logo

### ISSUE THREAD

**Issue by FastGeert** [gigforks/gitea#8]
We can't really be proud of this.

![image](https://user-images.githubusercontent.com/15246294/32839447-bfcac042-ca14-11e7-9ab2-0b70d3559f35.png)

**Comment by ghost** [comment]
It is awful right now and it's only good for testing. 
Ideally we need to make IYO the primary way to login which means that IYO login must be it's own tab.

![login screen iyo gitea](https://user-images.githubusercontent.com/31761294/32889059-005f1a46-cad2-11e7-8812-970efc9ad6be.jpg)
(quick mockup excuse the alignment)

This would be the default tab shown when you click login. User/password can stay in a separate tab because we absolutely want to push people to use IYO in our deployment of gitea.

The whole big friendly button needs to be clickable.

**Comment by Dinaamagdy** [comment]
now only sign in option exist 
## Software Version 
f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e
